cache:
  paths:
    - node_modules/
    - .yarn

before_script:  
  - apt-get update -qq && apt-get install

stages:
  - binaries

Create binaries:
  stage: binaries
  tags:
    - saas-linux-medium-amd64

#   before_script:
#     - yarn install
  script:
    - yarn install
    # - yarn update-binaries && node copy-binaries-for-test.js && yarn docker-build
    - pkg . --compress Gzip --targets node16-linux-amd64 --out-path bin 
